# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l6eZXe_KCLZalZ7-3AX9G-RzJfJcj1wc
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib

# Configuração da página do Streamlit
st.set_page_config(
    page_title="Monitoramento de Qualidade do Ar - UNIMAR",
    page_icon="🌫️",
    layout="centered"
)

#Carregar os artefatos salvos pelo notebook
@st.cache_resource
def carregar_artefatos():
    modelo = joblib.load('modelo_qualidade_ar.pkl')
    scaler = joblib.load('scaler_qualidade_ar.pkl')
    return modelo, scaler

try:
    modelo, scaler = carregar_artefatos()
    artefatos_carregados = True
except Exception as e:
    artefatos_carregados = False

# Cabeçalho da aplicação
st.title("Sistema Preditivo de Qualidade do Ar")
st.markdown("""
Esta aplicação utiliza Inteligência Artificial (algoritmo **Random Forest**) para classificar a qualidade do ar em tempo real como **Boa** ou **Ruim**.
Desenvolvido como projeto prático para a disciplina de IA da **UNIMAR**.
""")

st.divider()

if not artefatos_carregados:
    st.error("Erro: Os arquivos 'modelo_qualidade_ar.pkl' e/ou 'scaler_qualidade_ar.pkl' não foram encontrados no diretório. Certifique-se de executar a célula de exportação do notebook primeiro!")
else:
    st.subheader("Insira as Medições Ambientais dos Sensores:")

    col1, col2 = st.columns(2)

    with col1:
        st.markdown("**Concentrações Gasosas**")
        co = st.number_input("Monóxido de Carbono - CO(GT)", min_value=0.0, max_value=15.0, value=2.1, step=0.1)
        pt08_co = st.number_input("Sensor Óxido de Estanho - PT08.S1(CO)", min_value=300.0, max_value=3000.0, value=1100.0, step=10.0)
        c6h6 = st.number_input("Benzeno - C6H6(GT)", min_value=0.0, max_value=70.0, value=10.2, step=0.1)
        pt08_nmhc = st.number_input("Sensor Titânia - PT08.S2(NMHC)", min_value=300.0, max_value=3000.0, value=950.0, step=10.0)
        nox = st.number_input("Óxidos de Nitrogênio - NOx(GT)", min_value=0.0, max_value=1500.0, value=180.0, step=5.0)
        pt08_nox = st.number_input("Sensor Óxidos de Nitrogênio - PT08.S3(NOx)", min_value=300.0, max_value=3000.0, value=800.0, step=10.0)
        no2 = st.number_input("Dióxido de Nitrogênio - NO2(GT)", min_value=0.0, max_value=500.0, value=110.0, step=5.0)

    with col2:
        st.markdown("**Condições Meteorológicas e Outros**")
        pt08_no2 = st.number_input("Sensor Dióxido de Nitrogênio - PT08.S4(NO2)", min_value=300.0, max_value=3000.0, value=1450.0, step=10.0)
        pt08_o3 = st.number_input("Sensor Ozônio - PT08.S5(O3)", min_value=300.0, max_value=3000.0, value=1020.0, step=10.0)
        temp = st.number_input("Temperatura Corporal/Ar (°C)", min_value=-10.0, max_value=50.0, value=18.5, step=0.1)
        rh = st.number_input("Umidade Relativa - RH (%)", min_value=0.0, max_value=100.0, value=45.0, step=0.5)
        ah = st.number_input("Umidade Absoluta - AH", min_value=0.0, max_value=3.0, value=0.95, step=0.01)

        st.markdown("**Variáveis Temporais (Sazonalidade)**")
        mes = st.selectbox("Mês de Coleta", options=list(range(1, 13)), index=5)
        dia_semana = st.selectbox("Dia da Semana (0=Seg, 6=Dom)", options=list(range(7)), index=2)
        hora = st.slider("Hora da Medição (0-23h)", min_value=0, max_value=23, value=12)
        estacao_selecionada = st.selectbox("Estação Climática", options=['Inverno', 'Primavera', 'Verão', 'Outono'])

        estacao_dict = {'Inverno': 0, 'Primavera': 1, 'Verão': 2, 'Outono': 3}
        estacao_cod = estacao_dict[estacao_selecionada]

    st.markdown("---")

    # Botão executar
    if st.button("ANALISAR QUALIDADE DO AR", use_container_width=True):

        dados_usuario = pd.DataFrame({
            'PT08.S1(CO)': [pt08_co],
            'C6H6(GT)': [c6h6],
            'PT08.S2(NMHC)': [pt08_nmhc],
            'NOx(GT)': [nox],
            'PT08.S3(NOx)': [pt08_nox],
            'NO2(GT)': [no2],
            'PT08.S4(NO2)': [pt08_no2],
            'PT08.S5(O3)': [pt08_o3],
            'T': [temp],
            'RH': [rh],
            'AH': [ah],
            'mes': [mes],           # Mês vem primeiro na ordem do notebook
            'dia_semana': [dia_semana], # Dia da semana vem em seguida
            'hora': [hora]          # Hora DEVE ser a última coluna
        })

        # Aplicar a normalização do Scaler original
        try:
            dados_normalizados = scaler.transform(dados_usuario)

            #Predição e cálculo probabilístico
            predicao = modelo.predict(dados_normalizados)[0]
            probabilidades = modelo.predict_proba(dados_normalizados)[0]

            st.subheader(" Resultado da Análise Estatística")

            #Exibição do diagnóstico do negócio (Assumindo 0=Boa e 1=Ruim)
            if predicao == 1:
                st.error(f"**ALERTA: QUALIDADE DO AR RUIM** (Confiança: {probabilidades[1]*100:.2f}%)")
                st.markdown("Recomenda-se evitar atividades físicas prolongadas ao ar livre para grupos de risco (crianças, idosos e cardiopatas).")
            else:
                st.success(f"**DIAGNÓSTICO: QUALIDADE DO AR BOA** (Confiança: {probabilidades[0]*100:.2f}%)")
                st.markdown("Atmosfera dentro dos parâmetros normativos aceitáveis de dispersão de poluentes urbanos.")

        except Exception as e:
            st.error(f"Erro no pré-processamento dos dados. Verifique se a ordem e quantidade de colunas coincidem com o esperado pelo modelo. Detalhe: {e}")


st.markdown("---")
st.caption("Projeto Desenvolvido por Felipe Dorta, Bruno Silva e Lucas Kopeska. UNIMAR - Inteligência Artificial.")